### ISSUE TITLE
Get Twitter data for a given time span

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/annual-report-help#2]
### Goal i.e. What question do we need to answer
How big is our twitter bubble? 😉

### What items do we need
- number of followers on a given date
- total number of mentions in a given time span 
- geographic locations of followers

### How to acquire these items
See Bob Rudis’s [21 recipes for Mining Twitter data with rtweet](https://rud.is/books/21-recipes/index.html)
- number of followers on a given date using e.g. [`rtweet::get_followers()`](https://rud.is/books/21-recipes/harvesting-friends-and-followers.html)
- geographic locations of followers using e.g. [rtweet & Google geocoding API function from the ggmaps package](https://rud.is/books/21-recipes/geocoding-locations-from-profiles-or-elsewhere.html)

Code should produce these numbers for some input time span, where possible (e.g. 12-months, all time) so we can re-run any time.

I (@stefaniebutland) have some monthly twitter analytics data collected for # of followers, # of mentions etc and can share that if helpful.

### Examples
This analysis from useR!2019 by John Alexis Guerra Gómez was nice (but it's far more than we would use in a report): Twitter influencers for #useR2019. [A visual story on how to find the most interesting people to follow for a Twitter topic](https://johnguerra.co/viz/influentials/story/?hashtag=useR2019)

**Comment by pachadotdev** [comment]
please please me (8) @stefaniebutland

**Comment by stefaniebutland** [comment]
Thank you @pachamaltese ! 
We'll answer any questions you have asap.

**Comment by pachadotdev** [comment]
do you see value in using network measures such as those provided in `economiccomplexity`?

**Comment by pachadotdev** [comment]
I'll start capturing tweets tonight. Which year do you consider a desirable start?

**Comment by stefaniebutland** [comment]
> do you see value in using network measures such as those provided in economiccomplexity?

Maybe, however, right now I think the biggest value is in getting some basic information.

I have a *lot* of tweets already downloaded. Let me check on making those public.

**Comment by pachadotdev** [comment]
I have a sketch with last week of tweets. I'm eager to use the archive

**Comment by stefaniebutland** [comment]
Here it is @pachamaltese https://github.com/ropenscilabs/ropensci-tweets

Note that I don't _think_ you actually need this data to produce the basic items we think we need

**Comment by pachadotdev** [comment]
so sorry, it's national week here, the country is at 30% of its capacity and there were some isp problems

here's my approach: https://github.com/pachamaltese/ropensci-tweets-location
it should be run every X days, since the followers don't come with a date, you need to start with a stock of Y followers on day X, and then capture followers again to determine the growth rate

I captured followers with location and the other requirements and I sent Stefanie the .Rprofile on slack, as I had to create the "rOpenSci tweets" app from google dashboard and generate a token

**Comment by stefaniebutland** [comment]
Thank you for this @pachamaltese, especially during isp vacation ;-)

Could you please add a README to explain how you addressed the question, what you did, datasets you used, to a person like me who is not familiar with the code, or like Scott who doesn't typically work with twitter data and wonders what "friends" means?

**Comment by pachadotdev** [comment]
Sure! Now I can visualize, addd readme, etc. I shall do it soon. The hard
part was to re-try downloading a lot bc of connection problems.

**Comment by pachadotdev** [comment]
ready, I added a readme in the repo

**Comment by pachadotdev** [comment]
@stefaniebutland Hi, when you have time, can you create a Twitter app or give me access to do that? I have an app but it gets the mentions to @pachamaltese provided Twitter's API gets mentions relative to the authenticated user via tokens

**Comment by stefaniebutland** [comment]
@pachamaltese for total number of mentions in a given time span, I was thinking you could get that from [this file](https://github.com/ropenscilabs/ropensci-tweets/blob/master/twitter_metrics_monthly_rOpenSci.csv) whose provenance is described in the [README](https://github.com/ropenscilabs/ropensci-tweets). 

I'll have a look at the rest ~later today~ Monday.

**Comment by pachadotdev** [comment]
Sure! I misunderstood something from the other posts. In that case it's
easy, I'll send a PR later today

**Comment by pachadotdev** [comment]
ready, back to the office and now with normal internet connection
I did a basic EDA w.r. to +mentions

**Comment by stefaniebutland** [comment]
Here are some comments. Please keep in mind I'm an R beginner, with the perspective of wanting to be able to run this when needed and put the results into a couple of sentences of text like "On <date> rOpenSci had <f> followers on Twitter from <c> countries. In the past year <date span>, people have mentioned rOpenSci <m> times on Twitter.  

To facilitate that, could you please add an output file from which we could get that information most easily? e.g. 
- number of followers: f
- number of countries: c
- number of mentions: m

For geolocation, what I'd really like is number of as countries above, if possible.

We won't use "friends" because rOpenSci intentionally does not follow many accounts, so perhaps best to comment that out.

Please add to the README a listing of what each output file contains, and what each script does, if that's not already clear in README

Thank you

**Comment by pachadotdev** [comment]
Nice! I can do that :)
Thanks Stefanie

**Comment by pachadotdev** [comment]
Ready!! it wasn't exactly easy, but I got the summary with the output file as requested

**Comment by stefaniebutland** [comment]
Thank you @pachamaltese. I don't plan to ask for any new additions. I'll leave this issue open until I'm sure I don't have further questions.

**Comment by stefaniebutland** [comment]
@pachamaltese We’ll use some of your code in making our reports. Do you consent to us publicly acknowledging you for this (e.g. in a report)?

**Comment by pachadotdev** [comment]
Yes, please take, adapt and use as required!

**Comment by stefaniebutland** [comment]
Thank you. Closing this issue

**Comment by pachadotdev** [comment]
Btw, do you have more open tasks? I can. Take another one that is simpler

**Comment by stefaniebutland** [comment]
All closed now. Thank you for offering @pachamaltese

**Comment by stefaniebutland** [comment]
for the record, ropensci-tweets repo moved to https://github.com/ropensci-org/ropensci-tweets
