### ISSUE TITLE
Number of packages gone through software review

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/annual-report-help#5]
### Goal i.e. What question do we need to answer
 
How many packages have gone through software review?

### What items do we need

* List of packages, with metadata containing whether the package has gone through software review or not

### How to acquire these items

* Use rOpenSci registry https://github.com/ropensci/roregistry/  - use the https://github.com/ropensci/roregistry/blob/gh-pages/registry.json  file 
* if the `onboarding` field has a url it's gone through review or is going through review

**Comment by sharlagelfand** [comment]
:wave: I can't assign myself, but I'll take a stab at this!

**Comment by stefaniebutland** [comment]
Thank you @sharlagelfand !
We'll answer any questions you have asap if they come up

**Comment by pachadotdev** [comment]
+1 I can be assigned to this as well

**Comment by stefaniebutland** [comment]
Thank you @pachamaltese. I've assigned @sharlagelfand to this one, and assigned you to the Twitter issue https://github.com/ropenscilabs/annual-report-help/issues/2

It's possible there's a place for collaboration or code review, but I'll let @sharlagelfand take the lead here.

**Comment by pachadotdev** [comment]
thx, twitter then for now
just write me if there's something 2 be done

**Comment by sharlagelfand** [comment]
I've created [a repo](https://github.com/sharlagelfand/ropenscipackagesreviewed) with some analysis (number of packages gone through/in review, number by year, number of days in review), and the list of packages is available as a data frame in the package (meta!) as well as [in a CSV](https://github.com/sharlagelfand/ropenscipackagesreviewed/blob/master/data-raw/ropensci_packages.csv).

**Comment by sckott** [comment]
thanks @sharlagelfand this is really great!

A few requests:

- It looks like you're already grabbing data from Github for the issues. But it looks like you're scraping the issues pages https://github.com/sharlagelfand/ropenscipackagesreviewed/blob/master/data-raw/ropensci_packages.R#L24  - could you use the Github API <https://developer.github.com/v3/> instead? 
- And while using the Github API, getting labels for the issues would really help here. E.g., issues with a `holding` label should i think be excluded from any analyses
- Looks like you're using a closed issue as gone through review?  I'd instead use the GH labels, in particular this one https://github.com/ropensci/software-review/issues?q=is%3Aissue+is%3Aopen+label%3A6%2Fapproved , because that means the pkg is officially through review, and sometimes those issues aren't closed by their editors for quite a long time

**Comment by sharlagelfand** [comment]
thanks @sckott! 

i *think* i'm using the GitHub API since i'm just using the [gh package](https://github.com/r-lib/gh) and it seems like that's what it uses.

i updated the analysis to take issues with the "6/approved" label to have gone through review instead of a "closed" state. since there isn't a date attached to when that label is added in the API, most of the analysis had to go (👋) but i did keep a bit in based on when the issue was created (even though that's not necessarily the same year it was approved). i can take that out if it still doesn't make sense.

ty!

**Comment by sckott** [comment]
> i think i'm using the GitHub API

ah right, sorry about that, i thought that line with `http:.//github.com` was using that base url, my bad 😊 

---

wrt label dates, i think we can get the date, just a different route https://api.github.com/repos/ropensci/software-review/issues/332/events?page=3 which matches the date the label was applied https://github.com/ropensci/software-review/issues/332#issuecomment-529212658 Would that work?

**Comment by sharlagelfand** [comment]
yes, it would! i was totally being lazy and didn't see that. let me look into it 🔍

**Comment by sharlagelfand** [comment]
ok 👍 i updated the repo now using the date that label was added.

i might do some more analysis of the time in different stages out of curiosity but i probably shouldn't commit to that (in case i get distracted by something else 😬), but i'll definitely let you all know if i end up looking at it! 

hope this is helpful!

**Comment by sckott** [comment]
great, thx very much Sharla! looks good

**Comment by stefaniebutland** [comment]
@sharlagelfand Thank you so much for contributing this solution! We’ll use your code in making our reports. Do you consent to us publicly acknowledging you for this (e.g. in a report)?

**Comment by sharlagelfand** [comment]
@stefaniebutland my pleasure! I do, thanks very much 😊
