### ISSUE TITLE
Number of reviewers

### ISSUE THREAD

**Issue by cboettig** [ropenscilabs/annual-report-help#6]
## Goal i.e. What question do we need to answer

What's our total reviewer pool? Is it growing over time?  Are fewer people doing more reviews, or more reviewers make fewer work for everyone? Who has reviewed the most in a given year?  Who gets a prize?!

## What items do we need

- Total number of people who have served as a reviewer.  
- names / GitHub usernames / ORCID IDs of all reviewers
- Number of reviews each reviewer handled, date review began, date review finished, review outcome.  

## How to acquire these items

- GitHub API commands applied to software-review Issues.  

Also may be related to #5

**Comment by stefaniebutland** [comment]
Closing with @cboettig's permission. We have some private data to address this issue
